modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "Apache 2.0"

[[mods]]
modId = "cosmetica"
version = "${version}"
displayName = "Cosmetica"
authors = "Valoeghese, Eyezah"
description = '''
Custom Cosmetics for Free, Forever.
'''
logoFile = "assets/cosmetica/icon.png"

[[dependencies.cosmetica]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cosmetica]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.7,1.21.10)"
ordering = "NONE"
side = "BOTH"
