plugins {
    id "com.gradleup.shadow" version "9.2.2"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

repositories {
    maven { url 'https://maven.terraformersmc.com/' }
    maven {
        url 'https://www.jitpack.io'
    }
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    api ("net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}") {
        exclude module: "fabric-loader"
    }
    include(fabricApi.module("fabric-resource-loader-v1", "${project.fabric_api_version}"))
    include(fabricApi.module("fabric-api-base", "${project.fabric_api_version}"))

    // Cosmetica Core
    include(implementation "cc.cosmetica:cosmetica-core-fabric:${rootProject.core_version}-${rootProject.minecraft_version}")
    // Kupe
    include(implementation "cc.cosmetica:kupe-fabric:${rootProject.kupe_version}-${rootProject.minecraft_version}")
    // Webp Support
    include(implementation "com.twelvemonkeys.imageio:imageio-webp:${rootProject.imaging_version}")
    include "com.twelvemonkeys.imageio:imageio-core:${rootProject.imaging_version}"
    include "com.twelvemonkeys.imageio:imageio-metadata:${rootProject.imaging_version}"
    include "com.twelvemonkeys.common:common-lang:${rootProject.imaging_version}"
    include "com.twelvemonkeys.common:common-io:${rootProject.imaging_version}"
    include "com.twelvemonkeys.common:common-image:${rootProject.imaging_version}"

    // Mod Menu (for Compat)
    implementation "com.terraformersmc:modmenu:18.0.0-alpha.8"

    common(project(path: ":common")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

jar {
    archiveClassifier = "raw"
}

shadowJar {
    dependsOn(jar)
    mainSpec.sourcePaths.clear()       // Remove default source set inclusion
    from(zipTree(jar.archiveFile))     // Unpack jar output (preserves Loom modifications)

    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null           // shadowJar becomes the main artifact
}

//remapJar {
//    injectAccessWidener = true
//    input.set shadowJar.archiveFile
//    dependsOn shadowJar
//}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

//components.java {
//    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
//        skip()
//    }
//}

// use shadowjar for maven on 26.1
configurations {
    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}
