org.gradle.jvmargs=-Xmx2048M

minecraft_version=26.2
enabled_platforms=fabric,neoforge

archives_base_name=cosmetica
mod_version=2.0.1
maven_group=cc.cosmetica

fabric.loom.disableObfuscation=true

#architectury_version=1.32.68

fabric_loader_version=0.19.3
fabric_api_version=0.153.0+26.2

forge_version=26.1-62.0.3

neoforge_version=26.2.0.7-beta

kupe_version=0.26.10
core_version=2.1.7
imaging_version=3.12.0
