plugins {
    id "com.github.johnrengelman.shadow" version "8.1.1"
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

//    neoForge {
//        convertAccessWideners = true
        //extraAccessWideners.add loom.accessWidenerPath.get().asFile.name
//    }
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    shadowCommon { // Don't use shadow from the shadow plugin since it *excludes* files.
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

dependencies {
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"

    // Cosmetica Core
    modImplementation "cc.cosmetica:cosmetica-core-neoforge:${rootProject.core_version}-${rootProject.minecraft_version}"
    // Kupe Core
    modImplementation "cc.cosmetica:kupe-neoforge:${rootProject.kupe_version}-${rootProject.minecraft_version}"
    // Webp Support
    implementation "com.twelvemonkeys.imageio:imageio-webp:${rootProject.imaging_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive = false }

    // jarJar core and kupe
    include "cc.cosmetica:cosmetica-core-neoforge:${rootProject.core_version}-${rootProject.minecraft_version}"
    include "cc.cosmetica:kupe-neoforge:${rootProject.kupe_version}-${rootProject.minecraft_version}"
    // Shadow twelvemonkeys
    shadow "com.twelvemonkeys.imageio:imageio-core:${rootProject.imaging_version}"
    shadow "com.twelvemonkeys.imageio:imageio-webp:${rootProject.imaging_version}"
    shadow "com.twelvemonkeys.imageio:imageio-metadata:${rootProject.imaging_version}"
    shadow "com.twelvemonkeys.common:common-lang:${rootProject.imaging_version}"
    shadow "com.twelvemonkeys.common:common-io:${rootProject.imaging_version}"
    shadow "com.twelvemonkeys.common:common-image:${rootProject.imaging_version}"
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

//    relocate 'cc.cosmetica.kupe', 'cc.cosmetica.include.kupe'
    relocate 'com.twelvemonkeys', 'cc.cosmetica.include.twelvemonkeys'
    // needs to be the same as core
    relocate 'org.apache.hc', 'cc.cosmetica.org.apache.hc'
    relocate 'org.slf4j', 'cc.cosmetica.org.slfj'
    relocate 'org.openapitools.jackson', 'cc.cosmetica.org.openapitools.jackson'
    relocate 'com.fasterxml.jackson', 'cc.cosmetica.com.fasterxml.jackson'
    exclude 'javax/**'
    exclude 'org/apache/commons/**'

    transform(com.github.jengelman.gradle.plugins.shadow.transformers.AppendingTransformer) {
        resource = 'META-INF/neoforge.mods.toml'
    }

    mergeServiceFiles()

    configurations = [project.configurations.shadowCommon, project.configurations.shadow]
    archiveClassifier = "dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenForge(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}
